# SPDX-FileCopyrightText: 2022 MDAD project contributors
# SPDX-FileCopyrightText: 2024 wjbeckett
# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of LiveKit Server service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ livekit_server_identifier }}.service"
  register: livekit_server_service_stat

- name: Uninstall LiveKit Server systemd services and files
  when: livekit_server_service_stat.stat.exists | bool
  block:
    - name: Ensure LiveKit Server is stopped
      ansible.builtin.service:
        name: "{{ livekit_server_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure LiveKit Server systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ livekit_server_identifier }}.service"
        state: absent

    - name: Ensure LiveKit Server container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ livekit_server_container_network }}"
        state: absent

    - name: Ensure LiveKit Server container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ livekit_server_container_network }}
      register: network_deletion_result
      changed_when: livekit_server_container_network in network_deletion_result.stdout

    - name: Ensure LiveKit Server path does not exist
      ansible.builtin.file:
        path: "{{ livekit_server_base_path }}"
        state: absent
